bitproje/Controllers/EgitimlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using bitproje.Data;
using bitproje.Entitys;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace bitproje.Controllers
{
    public class EgitimlerController : Controller
    {
        private readonly isgContext _context;

        public EgitimlerController(isgContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var egitim = await _context.Egitimler.OrderBy(b => b.Egitimid).ToListAsync();
                foreach (var item in egitim)
                {
                    item.kullanici = (_context.Kullanici.FirstOrDefault(b => b.Sicilno == item.Sicilno));

                } return View(egitim);
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult Grupegitim()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var bul =  _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmagrubuid"));
            var kullanicii =  _context.Kullanici.Where(b => b.Grupid == bul.GrupId);
            var egitim = new List<Egitimler>();
            foreach (var i in kullanicii)  //
            {
                var eg= _context.Egitimler.Where(c => c.Sicilno == i.Sicilno);
                
                foreach (var j in eg)
                {
                    j.kullanici = _context.Kullanici.FirstOrDefault(b=>b.Sicilno==j.Sicilno);
                    egitim.Add(j);

                }
            }            

            return View("Index", egitim);
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult Firmaegitim()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var bul = _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmaid"));
            var kullanicii = _context.Kullanici.Where(b => b.Grupid == bul.GrupId);
            var egitim = new List<Egitimler>();
            foreach (var i in kullanicii)  //
            {
                var eg = _context.Egitimler.Where(c => c.Sicilno == i.Sicilno);

                foreach (var j in eg)
                {
                    j.kullanici = _context.Kullanici.FirstOrDefault(b => b.Sicilno == j.Sicilno);
                    egitim.Add(j);

                }
            }

            return View("Index", egitim);
            }
            else
            {
                return NotFound();
            }
        }
        public IActionResult kulFirmaegitim()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var egitim = _context.Egitimler.Where(b => b.Sicilno.ToString() == HttpContext.Session.GetString("sicilno"));
            
            foreach (var i in egitim)  //
            {
                i.kullanici = _context.Kullanici.FirstOrDefault(c => c.Sicilno == i.Sicilno);

            }

            return View("Index", egitim);
        }
            else
            {
                return NotFound();
    }
     }


        public IActionResult Create()
        {
            var egitim = new Egitimler();
            if (HttpContext.Session.GetString("grubu") == "A")
            {
                var bul = _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmagrubuid"));
                var kullanici = new List<Kullanici>( _context.Kullanici.Where(b => b.Grupid == bul.GrupId && b.Gorevtanim == "İşyeri Güvenliği Uzmanı"));              
                ViewBag.mkullanici = kullanici;
            }
             else  if (HttpContext.Session.GetString("grubu") == "D")
            {
                var kul = _context.Kullanici.FirstOrDefault(b => b.Sicilno.ToString() == HttpContext.Session.GetString("sicilno"));
                egitim.Sicilno = kul.Sicilno;
                egitim.kullanici = kul;
            }
            else
            {
                return NotFound();
            }


            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Egitimtrh,Egitimalani,Toplamsure,Aciklama,Egitimkonulari,Sicilno")]
        Egitimler eg)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eg);
                await _context.SaveChangesAsync();
                if (HttpContext.Session.GetString("grubu") == "A") { return RedirectToAction(nameof(Grupegitim)); }
                else if (HttpContext.Session.GetString("grubu") == "D") { return RedirectToAction(nameof(kulFirmaegitim)); }
            }

            return View(eg);

        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var egitim = await _context.Egitimler.FindAsync(id);
            if (egitim == null)
            {
                return NotFound();
            }
            if (HttpContext.Session.GetString("grubu") == "A")
            {
                var bul = _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmagrubuid"));               
                var kullanici = new List<Kullanici>(_context.Kullanici.Where(b => b.Grupid == bul.GrupId && b.Gorevtanim == "İşyeri Güvenliği Uzmanı"));
                
                ViewBag.mkul = kullanici;
            }
            else if (HttpContext.Session.GetString("grubu") == "D")
            {
                var bul =_context.Kullanici.FirstOrDefault(b => b.Sicilno==egitim.Sicilno);
                egitim.kullanici = bul; 
            }
            else
            {
                return NotFound();
            }

            return View(egitim);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Egitimid,Egitimtrh,Egitimalani,Toplamsure,Aciklama,Egitimkonulari,Sicilno")]
        Egitimler eg)
        {
            if (id != eg.Egitimid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eg);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EgitimExists(eg.Egitimid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if (HttpContext.Session.GetString("grubu") == "A") { return RedirectToAction(nameof(Grupegitim)); }
                else if (HttpContext.Session.GetString("grubu") == "D") { return RedirectToAction(nameof(kulFirmaegitim)); }
            }

            return View(eg);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (HttpContext.Session.GetString("grubu") == "A" || HttpContext.Session.GetString("grubu") == "D")
            {
                var egitim = _context.Egitimler
                .FirstOrDefault(m => m.Egitimid == id);
                egitim.kullanici = _context.Kullanici.FirstOrDefault(b => b.Sicilno == egitim.Sicilno);
                if (egitim == null)
                {
                    return NotFound();
                }
                return View(egitim);
            }
            else
            {
                return NotFound();
            }

        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eg = _context.Egitimler.FirstOrDefault(m => m.Egitimid == id);
            _context.Egitimler.Remove(eg);
            await _context.SaveChangesAsync();
            if (HttpContext.Session.GetString("grubu") == "A") { return RedirectToAction(nameof(Grupegitim)); }
            else if (HttpContext.Session.GetString("grubu") == "D") { return RedirectToAction(nameof(kulFirmaegitim)); }
            return View();
        }


        private bool EgitimExists(int id)
        {
            return _context.Muayene.Any(e => e.Mid == id);
        }


    }
}

bitproje/Controllers/KatilimcilarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using bitproje.Data;
using bitproje.Entitys;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace bitproje.Controllers
{
    public class KatilimcilarController : Controller
    {
        private readonly isgContext _context;

        public KatilimcilarController(isgContext context)
        {
            _context = context;
        }
        public IActionResult Index(int? id)
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var katilim = _context.Katilimcilar.Where(b => b.Egitimid == id);
            foreach (var item in katilim)
            {
                item.egitim = _context.Egitimler.FirstOrDefault(c => c.Egitimid == item.Egitimid);
                item.personel = _context.Personel.FirstOrDefault(b => b.Sicilnop == item.Sicilnop);
            }
            ViewBag.egitimid = id;
            return View(katilim);

            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult Create(int? id)
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {

                var katilim = new Katilimcilar();
            katilim.Egitimid = id;

            var grup = _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmagrubuid"));
            var firmalar = new List<Firma>(_context.Firma.Where(m => m.GrupId == grup.GrupId));
            var katpersonel = new List<Personel>();
            foreach (var i in firmalar)
            {
                var per = _context.Personel.Where(b => b.Firmaid == i.Firmaid);
                foreach (var j in per )
                {
                    if (_context.Katilimcilar.FirstOrDefault(m => m.Sicilnop == j.Sicilnop && m.Egitimid == id) == null)
                    {
                        katpersonel.Add(j);
                    }
                }
            }

            ViewBag.per = katpersonel;

            return View(katilim);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Egitimid,Sicilnop,Basariyuzdesi")]
        Katilimcilar kat)
        {

            if (ModelState.IsValid)
            {

                _context.Add(kat);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Katilimcilar", new { id = kat.Egitimid });
            }

            return View(kat);

        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                if (id == null)
            {
                return NotFound();
            }

            var kat = await _context.Katilimcilar
                .FirstOrDefaultAsync(m => m.Katilimid == id);

            if (kat == null)
            {
                return NotFound();
            }
            kat.personel = _context.Personel.FirstOrDefault(d => d.Sicilnop == kat.Sicilnop);
            return View(kat);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var katilim = _context.Katilimcilar.FirstOrDefault(m => m.Katilimid == id);
            _context.Katilimcilar.Remove(katilim);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Katilimcilar", new { id = katilim.Egitimid });
        }

    }
}

bitproje/Views/Katilimcilar/Create.cshtml
@model bitproje.Entitys.Katilimcilar

@{
    ViewData["Title"] = "Create";
}
<script src="~/lib/jquery/dist/jquery.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>


<h4>KATILIMCI EKLE</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">KATILAN PERSONEL</label>
                <select asp-for="Sicilnop" class="form-control select">
                    @foreach (var k in ViewBag.per)
                    {
                        <option value="@k.Sicilnop">@k.Sicilnop /  @k.Ad  @k.Soyad  </option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">BAŞARI YÜZDESİ</label>
                <input asp-for="Basariyuzdesi" value="%" class="form-control" />
                <span asp-validation-for="Basariyuzdesi" class="text-danger"></span>
            </div>

            <input type="hidden" asp-for="Egitimid" />
            <div class="form-group">
                &emsp; &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                <input type="submit" value="EKLE" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-id="@Model.Egitimid">

        <img style="height:35px;" title="Listeye geri dön" src="~/images/Iconsmind-Outline-Back.ico" />
    </a>
</div>

<script>
    $(".select").select2();
</script>

bitproje/Views/Katilimcilar/Delete.cshtml
@model bitproje.Entitys.Katilimcilar

@{
    ViewData["Title"] = "Delete";
}


<style>
    dt {
        height: 28px;
    }
</style>

<br />
<div>
    <h style="color:red;">BU KATILIMCIYI SİLMEK İSTEDİĞİNİZE EMİN MİSİNİZ ?</h>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            KATILIMCI PERSONEL
        </dt>
        <dd>
            @Html.DisplayFor(model => model.personel.Sicilnop) /  @Html.DisplayFor(model => model.personel.Ad)   @Html.DisplayFor(model => model.personel.Soyad)
        </dd>
        <dt>
            BAŞARI YÜZDESİ
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Basariyuzdesi)
        </dd>

    </dl>

    <form asp-action="Delete">
        <a asp-action="Index" asp-route-id="@Model.Egitimid">LİSTEYE GERİ DÖN</a> &emsp;|&emsp;
        <input type="hidden" asp-for="Katilimid" />
        <input type="submit" style="font-size:13px;font-weight:bold;height:27px;width:70px;" value="SİL" class="btn btn-danger" />

    </form>
</div>

bitproje/Views/Katilimcilar/Index.cshtml
@model IEnumerable<bitproje.Entitys.Katilimcilar>
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "Index";
}

<br />
<br />

<p>
    @if (@Context.Session.GetString("grubu") == "A")
    {
    <i>&emsp;</i> <a asp-action="Create" asp-route-id="@ViewBag.egitimid"><i style="font-size:20px;" class="fas fa-plus-circle" title="ilaç ekle"></i> &nbsp;KATILIMCI EKLE</a>
    }
 </p>
<table class="table">
    <thead>
        <tr>
            <th>
                KATILIMCI PERSONEL
            </th>
            <th>
                BAŞARI YÜZDESİ
            </th>
            @if (@Context.Session.GetString("grubu") == "A")
            {
                <th></th>
            }
            </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.personel.Sicilnop) /  @Html.DisplayFor(modelItem => item.personel.Ad)  @Html.DisplayFor(modelItem => item.personel.Soyad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Basariyuzdesi)
            </td>

            @if (@Context.Session.GetString("grubu") == "A")
            {
                <td>

                    <a asp-action="Delete" asp-route-id="@item.Katilimid"><i class="fas fa-trash-alt" title="KATILIMCIYI ÇIKAR"></i></a>
                </td>
            }
            </tr>
        }
    </tbody>
</table>
<div>
    @if (@Context.Session.GetString("grubu") == "A")
    {
        <a asp-action="Grupegitim" asp-controller="Egitimler">

            <img style="height:35px;" title="Listeye geri dön" src="~/images/Iconsmind-Outline-Back.ico" />
        </a>
    }
    else if (@Context.Session.GetString("grubu") == "B")
    {
        <a asp-action="Firmaegitim" asp-controller="Egitimler">

            <img style="height:35px;" title="Listeye geri dön" src="~/images/Iconsmind-Outline-Back.ico" />
        </a>
    }
</div>