bitproje/Controllers/FirmaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using bitproje.Data;
using bitproje.Entitys;
using bitproje.Models;
using bitproje.Utility;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace bitproje.Controllers
{
    public class FirmaController : Controller
    {
        private readonly isgContext _context;

        public FirmaController(isgContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {

                var Context =_context.Firma.OrderBy(b=>b.Firmaid);
            return View(Context.ToList());
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult Grupfirma()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var bul = _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmagrubuid"));
            var firmalar = _context.Firma.Where(b => b.GrupId==bul.GrupId);

            return View("Index",firmalar);
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult Firmafirma()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var bul = _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmaid"));
            var firmalar = _context.Firma.Where(b => b.GrupId == bul.GrupId);
            return View("Index", firmalar);
            }
            else
            {
                return NotFound();
            }
        }
        public IActionResult KulFirma()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var kullanici =  _context.Kullanici.FirstOrDefault(m => m.Sicilno.ToString() == HttpContext.Session.GetString("sicilno"));
            var firmalar = _context.Firma.Where(b => b.GrupId == kullanici.Grupid);
            return View("Index", firmalar);
            }
            else
            {
                return NotFound();
            }
        }


        public IActionResult Degis()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var grup = _context.Firma.FirstOrDefault(s => s.Firmaid.ToString() == HttpContext.Session.GetString("firmaid"));
            var Context = _context.Firma.Where(b => b.GrupId==grup.GrupId);

            return View(Context.ToList());
            }
            else
            {
                return NotFound();
            }
        }


        public IActionResult Detayi(int? id)
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var firma = _context.Firma.FirstOrDefault(b => b.Firmaid == id);
            HttpContext.Session.SetString("firmaad", firma.Funvan);
            HttpContext.Session.SetString("firmaiid", firma.Firmaid.ToString());
            ViewBag.percount = _context.Personel.Count(b => b.Firmaid == id);
            ViewBag.birimcount = _context.Birim.Count(b => b.Firmaid == firma.Firmaid);

            var personel = _context.Personel.Where(c => c.Firmaid == firma.Firmaid);
            int top = 0;
            foreach (var i in personel) //muayene olan personel listesini buluyor o firmaya ait
            {
                top =top + _context.Muayene.Count(c => c.Sicilnop == i.Sicilnop);
              
            }
            ViewBag.muayenecount = top;
            return View(firma);
           }
            else
            {
                return NotFound();
            }
             }

        public IActionResult AIndex(int id)
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {

                var Context = _context.Firma.OrderBy(b => b.Firmaid).Where(s => s.GrupId == id);
                return View(Context.ToList());

            }
            else
            {
                return NotFound();
            }

        }

        public async Task<IActionResult> Profil()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {

                if (HttpContext.Session.GetString("firmaid") == null)
            {
                return NotFound();
            }

            var firma = await _context.Firma.FirstOrDefaultAsync(m => m.Firmaid.ToString() == HttpContext.Session.GetString("firmaid"));
            // String a = _context.Firmagruplari.FirstOrDefault(d => d.GrupId == firma.GrupId).GrupAd;

            firma.Grup = _context.Firmagruplari.FirstOrDefault(h => h.GrupId == firma.GrupId);
            //ViewBag.a = _context.Firmagruplari.FirstOrDefaultAsync(d => d.GrupId == firma.GrupId);
            if (firma == null)
            {
                return NotFound();
            }

            return View(firma);
            }
            else
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> ProfilEdit(int? id)
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                if (id == null)
            {
                return NotFound();
            }

            var firma = await _context.Firma.FindAsync(id);
            if (firma == null)
            {
                return NotFound();
            }
            
            return View(firma);
           }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ProfilEdit(int id, [Bind("Firmaid,Funvan,Isvrnadsoyad,Isvrngsm,Firmatlfn,Faks,Firmamail,Il,Ilce,Adres,Faaliyetalan,Sgksicil,Tehlikesinif,Grupsirket")] Firma firma)
        {
            if (id != firma.Firmaid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    baglantiSinifi bs = new baglantiSinifi();
                    string sorgu = "update firma set funvan='" + firma.Funvan + "',isvrnadsoyad='" + firma.Isvrnadsoyad + "',isvrngsm='" + firma.Isvrngsm + "',firmatlfn='" + firma.Firmatlfn + "',faks='" + firma.Faks + "',firmamail='" + firma.Firmamail + "',il='" + firma.Il + "',ilce='" + firma.Ilce + "',adres='" + firma.Adres + "',faaliyetalan='" + firma.Faaliyetalan + "',sgksicil='" + firma.Sgksicil + "',tehlikesinif='" + firma.Tehlikesinif + "',grupsirket='" + firma.Grupsirket + "' where firmaid=" + id;
                    bs.baglanti("güncelle", sorgu);
                    ViewBag.sonuc = "FİRMA Eklendi";
                    return RedirectToAction(nameof(Profil));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FirmaExists(firma.Firmaid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }


            }
            ViewData["GrupId"] = new SelectList(_context.Firmagruplari, "GrupId", "GrupId", firma.GrupId);
            return View(firma);
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                if (id == null)
            {
                return NotFound();
            }

            var firma = await _context.Firma.FirstOrDefaultAsync(m => m.Firmaid == id);
           // String a = _context.Firmagruplari.FirstOrDefault(d => d.GrupId == firma.GrupId).GrupAd;

            firma.Grup=_context.Firmagruplari.FirstOrDefault(h=>h.GrupId==firma.GrupId);
            //ViewBag.a = _context.Firmagruplari.FirstOrDefaultAsync(d => d.GrupId == firma.GrupId);
            Console.WriteLine("olmadııııııııııııııııııııııııııııııııııııııııııııııı"+ViewBag.Grupu);
            if (firma == null)
            {
                return NotFound();
            }

            return View(firma);
            }
            else
            {
                return NotFound();
            }
        }
         public IActionResult Create()
        {
            if (HttpContext.Session.GetString("grubu") == "A" || HttpContext.Session.GetString("grubu") == "B" && HttpContext.Session.GetString("firmafirmaekle") == true.ToString() || HttpContext.Session.GetString("grubu") == "C" && HttpContext.Session.GetString("hekimfirmaekle") == true.ToString()
                || HttpContext.Session.GetString("grubu") == "D" && HttpContext.Session.GetString("uzmanfirmaekle") == true.ToString())
            {
                ViewBag.Gruplar = new List<Firma>(_context.Firma.Where(a => a.Durum == "Ana Firma"));

                return View();
            }           
            else
            {
                return NotFound();
            }
            

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Funvan,Isvrnadsoyad,Isvrngsm,Firmatlfn,Faks,Firmamail,Il,Ilce,Adres,Faaliyetalan,Sgksicil,Tehlikesinif,Grupsirket,GrupId")]
        Firma fir)
        {
            if (ModelState.IsValid)
            {
                if (HttpContext.Session.GetString("grubu") == "A")
                {
                    var grupf = _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmagrubuid"));

                    baglantiSinifi bs = new baglantiSinifi();
                    string sorgu = "insert into firma(funvan,isvrnadsoyad,isvrngsm,firmatlfn,faks,firmamail,il,ilce,adres,faaliyetalan,sgksicil,tehlikesinif,grupsirket,durum,grup_id) values" +

bitproje/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using bitproje.Data;
using bitproje.Entitys;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace bitproje.Controllers
{
    public class RegisterController : Controller
    {
        private readonly isgContext _context;

        public RegisterController(isgContext context)
        {
            _context = context;
        }

        public IActionResult FirmaKayit(int id)
        {
            var reg = new Register();
            reg.Firmaid = id;
            return View(reg);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FirmaKayit([Bind("Firmaid,soru,cevap,renk,Sifre,SifreTekrar,Kullaniciadi")] Register res)
        {
            if (ModelState.IsValid)
            {
               
                if (res.Sifre != res.SifreTekrar)
                {
                    ViewBag.sonuc = "SİFRE VE SİFRE TEKRARI AYNI DEĞİL.";
                }

                else if (_context.Users.FirstOrDefault(z => z.Kullaniciadi == res.Kullaniciadi) == null)
                {
                    var user = new Users();
                    user.Firmaid = res.Firmaid;
                    user.soru = res.soru;
                    user.cevap = res.cevap;
                    user.renk = res.renk;
                    user.Sifre = res.Sifre;
                    user.Kullaniciadi = res.Kullaniciadi;
                    user.Grubu = "B";
                    _context.Add(user);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("ISGM", "Home");                    
                    
                }
              
                else {
                    ViewBag.sonuc = "BÖYLE BİR KULLANICI ADI ZATEN VAR";
                }
            }
            return View(res);
        }
        

        public IActionResult SifreYenile(int id)
        {
            var us = _context.Users.FirstOrDefault(z => z.Id == id);
            var reg = new Register();
            reg.Id = us.Id;
            
            return View(reg);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SifreYenile(int id,[Bind("Id,Sifre,SifreTekrar")] Register res)
        {
            if (ModelState.IsValid)
            {

                if (res.Sifre != res.SifreTekrar)
                {
                    ViewBag.sonuc = "SİFRE VE SİFRE TEKRARI AYNI DEĞİL.";
                }

                else 
                {
                    var user = _context.Users.FirstOrDefault(z => z.Id == id);
                    user.Sifre = res.Sifre;
                    _context.Update(user);
                    await _context.SaveChangesAsync();

                    return RedirectToAction("ISGM", "Home");

                }
            }
            return View(res);
        }


        public IActionResult SifreSifirla(int id)
        {
            var us = _context.Users.FirstOrDefault(z => z.Id == id);           

            return View(us);
        }
        [HttpPost, ActionName("SifreSifirla")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SifreSifirlaConfirmed(int id)
        {
            var us = _context.Users.FirstOrDefault(m => m.Id == id);
            us.Sifre = "sıfırIsgm";
            _context.Update(us);
            await _context.SaveChangesAsync();
            return RedirectToAction("Yönetim", "Grup");
        }






        public IActionResult BilgiGüncelle()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var us = _context.Users.FirstOrDefault(z => z.Id.ToString() == HttpContext.Session.GetString("id"));
            var reg = new Register();
            reg.Id = us.Id;
            reg.Kullaniciadi = us.Kullaniciadi;
            reg.Sifre = us.Sifre;
            reg.SifreTekrar = us.Sifre;
            reg.renk = us.renk;
            reg.soru = us.soru;
            reg.cevap = us.cevap;

            return View(reg);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BilgiGüncelle(int id, [Bind("Id,Sifre,SifreTekrar,Kullaniciadi,renk,soru,cevap")] Register res)
        {
            if (ModelState.IsValid)
            {

                if (res.Sifre != res.SifreTekrar)
                {
                    ViewBag.sonuc = "SİFRE VE SİFRE TEKRARI AYNI DEĞİL.";
                }
                else if (_context.Users.FirstOrDefault(z => z.Kullaniciadi == res.Kullaniciadi && z.Id!=res.Id) == null)
                { 
                    var user = _context.Users.FirstOrDefault(z => z.Id == id);
                    user.Sifre = res.Sifre;
                    user.Kullaniciadi = res.Kullaniciadi;
                    user.renk = res.renk;
                    user.soru = res.soru;
                    user.cevap = res.cevap;
                    _context.Update(user);
                    await _context.SaveChangesAsync();

                    return RedirectToAction("Index", "Users");

                }
                else
                {
                    ViewBag.sonuc = "BÖYLE BİR KULLANICI ADI ZATEN VAR";

                }
            }
            return View(res);
        }


    }
}

bitproje/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bitproje</title>


    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
              integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
              crossorigin="anonymous" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
  
    <script>
        if(@Context.Session.GetString("grubu") == null)
        {
            window.location.href = "~/Views/Users/_Index.cshtml";
        }

    </script>
</head>




<body>


    <partial name="_header.cshtml" />

    <partial name="_CookieConsentPartial" />


    <br /><br />
    <br />


    <div style="background-color:honeydew;border-style:inherit;height:500px;border-width:unset;" class="col-md-3">
        <partial name="_menu" />
    </div>

    <div class="col-md-9">
        

        <div class="container-fluid" style="background-color:honeydew;">
            <div class="body-content">
                @RenderBody()
                <hr style="width:900px;" />
                <br />
                <footer>
                    <p>&copy; 2019 - bitproje</p>
                </footer>

            </div>
        </div>



    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

bitproje/Views/Shared/_header.cshtml
<script>
        if(@Context.Session.GetString("grubu") == null)
        {
            window.location.href = "~/Views/Users/_Index.cshtml";
        }

</script>

@using Microsoft.AspNetCore.Http;
<header>
    <div class="container-fluid">

        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-header navbar-form">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>

                </button>

                <img style="height:65px;" src="~/images/den.png" />
            </div>

            <div class="col-md-8 navbar-collapse collapse" style="color:#808080;font-size:20px;">
                <br />
                &emsp;
                &emsp;  &emsp;  &emsp;
                " Kaza temenni ederek değil tedbir alarak önlenir."


            </div>
            <div class="col-md-4 pull-right">

                <ul class="nav navbar-nav pull-right">





                    @if (@Context.Session.GetString("grubu") == "A")
                    {
                        <li class="dropdown dropdown-user dropdown-dark">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">

                                <span>

                                    <label style="font-size:15px;"> </label>
                                    &emsp;&emsp;&emsp;<i class="fas fa-user-cog" style="font-size:35px;"></i><br />&nbsp;
                                    <span class="firmname" style="font-size:15px;">
                                        ADMİN
                                        SAYFASI
                                    </span>
                                </span>



                            </a>
                            <ul class="dropdown-menu dropdown-menu-default">
                                <li>
                                    <a asp-controller="Register" asp-action="BilgiGüncelle">
                                        <i class="fas fa-exchange-alt"></i> &nbsp; ŞİFRE DEGİŞTİR
                                    </a>

                                </li>
                                <li>
                                    <a asp-controller="Users" asp-action="logout">
                                        <i class="fas fa-sign-out-alt"></i>&nbsp; Çıkış yap
                                    </a>

                                </li>
                            </ul>
                        </li>
                    }
                    else if (@Context.Session.GetString("grubu") == "B")
                    {
                        <li class="dropdown dropdown-user dropdown-dark">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">

                                <span>

                                    <label style="font-size:15px;">  @Context.Session.GetString("isveren")</label>
                                    <i class="fas fa-user-cog" style="font-size:35px;"></i><br />&nbsp;
                                    <span class="firmname" style="font-size:15px;">
                                        @Context.Session.GetString("funvan")
                                        ( @Context.Session.GetString("durum"))
                                    </span>
                                </span>



                            </a>
                            <ul class="dropdown-menu dropdown-menu-default">
                                <li>
                                    <a asp-controller="Firma" asp-action="Profil">
                                        <i class="fas fa-exchange-alt"></i> &nbsp; Profil
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="Register" asp-action="BilgiGüncelle">
                                        <i class="fas fa-exchange-alt"></i> &nbsp; ŞİFRE DEGİŞTİR
                                    </a>

                                </li>
                                <li>
                                    <a asp-controller="Users" asp-action="logout">
                                        <i class="fas fa-sign-out-alt"></i>&nbsp; Çıkış yap
                                    </a>

                                </li>
                            </ul>
                        </li>
                    }
                    else if (@Context.Session.GetString("grubu") == "C")
                    {
                        <li class="dropdown dropdown-user dropdown-dark">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">

                                <span>

                                    <label style="font-size:15px;"> @Context.Session.GetString("ad") @Context.Session.GetString("soyad") </label>
                                    <i class="fas fa-user-cog" style="font-size:35px;"></i><br />&nbsp;
                                    <span class="firmname" style="font-size:15px;">
                                        @Context.Session.GetString("sicilno")
                                        (@Context.Session.GetString("görev") )
                                    </span>
                                </span>



                            </a>
                            <ul class="dropdown-menu dropdown-menu-default">
                                <li>
                                    <a asp-controller="Kullanici" asp-action="Profil">
                                        <i class="fas fa-exchange-alt"></i> &nbsp; Profil
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="Register" asp-action="BilgiGüncelle">
                                        <i class="fas fa-exchange-alt"></i> &nbsp; ŞİFRE DEGİŞTİR
                                    </a>

                                </li>
                                <li>
                                    <a asp-controller="Users" asp-action="logout">
                                        <i class="fas fa-sign-out-alt"></i>&nbsp; Çıkış yap
                                    </a>

                                </li>
                            </ul>
                        </li>
                    }
                    else if (@Context.Session.GetString("grubu") == "D")
                    {
                        <li class="dropdown dropdown-user dropdown-dark">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">

                                <span>

                                    <label style="font-size:15px;"> @Context.Session.GetString("ad") @Context.Session.GetString("soyad") </label>
                                    <i class="fas fa-user-cog" style="font-size:35px;"></i><br />&nbsp;
                                    <span class="firmname" style="font-size:15px;">
                                        @Context.Session.GetString("sicilno")
                                        (@Context.Session.GetString("görev") )
                                    </span>
                                </span>



                            </a>
                            <ul class="dropdown-menu dropdown-menu-default">
                                <li>
                                    <a asp-controller="Kullanici" asp-action="Profil">
                                        <i class="fas fa-exchange-alt"></i> &nbsp; Profil
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="Register" asp-action="BilgiGüncelle">
                                        <i class="fas fa-exchange-alt"></i> &nbsp; ŞİFRE DEGİŞTİR
                                    </a>

                                </li>
                                <li>
                                    <a asp-controller="Users" asp-action="logout">
                                        <i class="fas fa-sign-out-alt"></i>&nbsp; Çıkış yap
                                    </a>

                                </li>
                            </ul>
                        </li>

                    }


                </ul>
            </div>






        </nav>
    </div>

</header>