bitproje/Controllers/MuayeneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using bitproje.Data;
using bitproje.Entitys;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace bitproje.Controllers
{
    public class MuayeneController : Controller
    {
        private readonly isgContext _context;

        public MuayeneController(isgContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var aa =  await _context.Muayene.OrderBy(b=>b.Mid).ToListAsync();           
           
                foreach (var item in aa)
                {
                    item.SicilnoNavigation=(_context.Kullanici.FirstOrDefault(b=>b.Sicilno==item.Sicilno));
                    item.SicilnopNavigation = (_context.Personel.FirstOrDefault(b => b.Sicilnop == item.Sicilnop));
                }      
            
            return View(aa);
            }
            else
            {
                return NotFound();
            }
        }


        public IActionResult Grupmuayene()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var bul = _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmagrubuid"));
            var firmaa = _context.Firma.Where(b => b.GrupId == bul.GrupId);
            var personel = new List<Personel>();
            foreach (var i in firmaa)  //FİRMALARDAKİ PERSONEL LİSTESİNİ ALIYOR
            {
                var per = _context.Personel.Where(c => c.Firmaid == i.Firmaid);
                foreach (var j in per)
                {

                    personel.Add(j);

                }
            }

            var muayene = new List<Muayene>();
            foreach (var i in personel) //muayene olan personel listesini buluyor o firma grubuna ait
            {
                var mua = _context.Muayene.Where(c => c.Sicilnop == i.Sicilnop);
                foreach (var j in mua)
                {
                    j.SicilnopNavigation = (_context.Personel.FirstOrDefault(b => b.Sicilnop == j.Sicilnop));
                    j.SicilnoNavigation = (_context.Kullanici.FirstOrDefault(b => b.Sicilno == j.Sicilno));
                    muayene.Add(j);
                   

                }
            }

            return View("Index", muayene);
            }
            else
            {
                return NotFound();
            }
        }
        public IActionResult Firmamuayene()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var personel = _context.Personel.Where(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmaiid"));        

            var muayene = new List<Muayene>();
            foreach (var i in personel) //muayene olan personel listesini buluyor o firmaya ait
            {
                var mua = _context.Muayene.Where(c => c.Sicilnop == i.Sicilnop);
                foreach (var j in mua)
                {
                    j.SicilnopNavigation = (_context.Personel.FirstOrDefault(b => b.Sicilnop == j.Sicilnop));
                    j.SicilnoNavigation = (_context.Kullanici.FirstOrDefault(b => b.Sicilno == j.Sicilno));
                    muayene.Add(j);


                }
            }

            return View("Index", muayene);
        }
            else
            {
                return NotFound();
            }
              }
        public IActionResult kullaniciFirmamuayene()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var personel = _context.Personel.Where(b => b.Firmaid.ToString() == HttpContext.Session.GetString("kfirmaid"));

            var muayene = new List<Muayene>();
            foreach (var i in personel) //muayene olan personel listesini buluyor o firmaya ait
            {
                var mua = _context.Muayene.Where(c => c.Sicilnop == i.Sicilnop && c.Sicilno.ToString()== HttpContext.Session.GetString("sicilno"));
                foreach (var j in mua)
                {
                    j.SicilnopNavigation = (_context.Personel.FirstOrDefault(b => b.Sicilnop == j.Sicilnop));
                    j.SicilnoNavigation = (_context.Kullanici.FirstOrDefault(b => b.Sicilno == j.Sicilno));
                    muayene.Add(j);


                }
            }

            return View("Index", muayene);
            }
            else
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var muayene =await _context.Muayene.FirstOrDefaultAsync(m => m.Mid == id);
            muayene.SicilnoNavigation = _context.Kullanici.FirstOrDefault(h => h.Sicilno == muayene.Sicilno);
            muayene.SicilnopNavigation = _context.Personel.FirstOrDefault(h => h.Sicilnop == muayene.Sicilnop);
            if (muayene == null)
            {
                return NotFound();
            }
           
           var recete = _context.Recete.FirstOrDefault(m => m.Mid == id);
            ViewBag.bos = "dolu";
            if(recete==null)
            {
                ViewBag.bos = null;
            }
            return View( Tuple.Create<Muayene,Recete>(muayene,recete));
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult Create()
        {
            var muayene = new Muayene();
            if (HttpContext.Session.GetString("grubu") == "A") { 
                var bul = _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmagrubuid"));
                var firmaa = _context.Firma.Where(b => b.GrupId == bul.GrupId);
                var personel = new List<Personel>();
                var kullanici = new List<Kullanici>(_context.Kullanici.Where(b=>b.Grupid==bul.GrupId && b.Gorevtanim=="İşyeri Hekimi"));
                foreach (var i in firmaa)  //FİRMALARDAKİ PERSONEL LİSTESİNİ ALIYOR
                {
                    var per = _context.Personel.Where(c => c.Firmaid == i.Firmaid);
                    foreach (var j in per)
                    {

                        personel.Add(j);

                    }
                   
                }
                ViewBag.mpersonel = personel;
                ViewBag.mkullanici = kullanici;
            }
            else if (HttpContext.Session.GetString("grubu") == "C")
            {                
                var personel = _context.Personel.Where(a => a.Firmaid.ToString() == HttpContext.Session.GetString("kfirmaid"));
                var kullanici = _context.Kullanici.FirstOrDefault(b => b.Sicilno.ToString() == HttpContext.Session.GetString("sicilno"));
                muayene.Sicilno = kullanici.Sicilno;
                ViewBag.mpersonel = personel;
                ViewBag.mkullanici = kullanici;
            }
            else { return NotFound(); }



            return View(muayene);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Mneden,Mtarihi,Sonrakimtarih,Annehastalikg,Babahastalikg,Kardeshastalikg,Cocukhastalikg,Büyüktan,Kücüktan,Nabiz,Kilo,Boy,Kangrup,Sicilno,Sicilnop,Grupid")]
        Muayene mu)
        {
            if (ModelState.IsValid)
            {
               
                _context.Add(mu);
                await _context.SaveChangesAsync();
                if (HttpContext.Session.GetString("grubu") == "A") { return RedirectToAction(nameof(Grupmuayene)); }
                else if (HttpContext.Session.GetString("grubu") == "C") { return RedirectToAction(nameof(kullaniciFirmamuayene)); }
               
            }

            return View(mu);

        }



        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var muayene = await _context.Muayene.FindAsync(id);
            if (muayene== null)
            {
                return NotFound();
            }
            if (HttpContext.Session.GetString("grubu") == "A")
            {
                var bul = _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmagrubuid"));
                var firmaa = _context.Firma.Where(b => b.GrupId == bul.GrupId);
                var personel = new List<Personel>();
                var kullanici = new List<Kullanici>(_context.Kullanici.Where(b => b.Grupid == bul.GrupId && b.Gorevtanim == "İşyeri Hekimi"));
                foreach (var i in firmaa)  //FİRMALARDAKİ PERSONEL LİSTESİNİ ALIYOR
                {
                    var per = _context.Personel.Where(c => c.Firmaid == i.Firmaid);
                    foreach (var j in per)
                    {

                        personel.Add(j);

                    }

                }
             
                ViewBag.mper = personel;
                ViewBag.mkul = kullanici;
            }
            else  if (HttpContext.Session.GetString("grubu") == "C")
            {
                var personel = _context.Personel.Where(b => b.Firmaid.ToString() == HttpContext.Session.GetString("kfirmaid"));   
                var kullanici = _context.Kullanici.FirstOrDefault(b => b.Sicilno.ToString() == HttpContext.Session.GetString("sicilno"));
                muayene.SicilnoNavigation = kullanici;
                ViewBag.mper = personel;
                ViewBag.mkul = kullanici;
            }
            else 
            {
                return NotFound();
            }

            return View(muayene);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

bitproje/Controllers/TanilarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using bitproje.Data;
using bitproje.Entitys;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace bitproje.Controllers
{
    public class TanilarController : Controller
    {
        private readonly isgContext _context;

        public TanilarController(isgContext context)
        {
            _context = context;
        }
        public IActionResult Index(int? id)
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var tanilar = _context.Tanilar.Where(b => b.Mid==id);
            ViewBag.mid = id;
             foreach (var item in tanilar)
            {
                item.Tanim = _context.Tanitanimi.FirstOrDefault(a => a.Tanitid == item.Tanimid);

            }
            return View(tanilar);
            }
            else
            {
                return NotFound();
            }
        }
        public IActionResult Create(int? id)
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var tani = new Tanilar();
            tani.Mid = id;
            var tanilar = new List<Tanitanimi>();
            var tanıtanım = _context.Tanitanimi;
            foreach (var i in tanıtanım)
            {
                if (_context.Tanilar.FirstOrDefault(m => m.Tanimid == i.Tanitid && m.Mid == id) == null)
                {
                    tanilar.Add(i);
                }
            }

            ViewBag.tani = tanilar;
            
            return View(tani);
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Mid,Tanimid")]
        Tanilar tan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tan);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Tanilar", new { id = tan.Mid });
            }

            return View(tan);

        }
        public IActionResult Delete(int? id)
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                if (id == null)
            {
                return NotFound();
            }

            var tan = _context.Tanilar.FirstOrDefault(s => s.Taniid == id);
            tan.Tanim = _context.Tanitanimi.FirstOrDefault(c => c.Tanitid == tan.Tanimid);
            if (tan == null)
            {
                return NotFound();
            }

            return View(tan);
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tanii = _context.Tanilar.FirstOrDefault(m => m.Taniid == id);
            _context.Tanilar.Remove(tanii);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Tanilar", new { id = tanii.Mid });
        }
    }
}

bitproje/Views/Tanilar/Create.cshtml
@model bitproje.Entitys.Tanilar

@{
    ViewData["Title"] = "Create";
}
<script src="~/lib/jquery/dist/jquery.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>


<h4>HASTAYA YENİ TANI EKLE</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">TANI</label>
                <select asp-for="Tanimid" class="form-control select">
                    @foreach (var k in ViewBag.tani)
                    {
                        <option value="@k.Tanitid">@k.Tanitid  /  @k.Taniadi </option>
                    }
                </select>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Mid" />
            <div class="form-group">

                &emsp; &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                <input type="submit" value="EKLE" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

<div>
    <a href="/Tanilar/Index/@Model.Mid"><img style="height:35px;" title="Listeye geri dön" src="~/images/Iconsmind-Outline-Back.ico" /></a>

</div>


<script>
    $(".select").select2();
</script>

bitproje/Views/Tanilar/Delete.cshtml
@model bitproje.Entitys.Tanilar

@{
    ViewData["Title"] = "Delete";
}

<h3>TANI </h3>
<br />


<div>
    <h style="color:red;">BU TANIYI SİLMEK İSTEDİĞİNİZE EMİN MİSİNİZ ?</h>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            TANI TANIMI
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tanim.Tanitid)  /   @Html.DisplayFor(model => model.Tanim.Taniadi)
        </dd>
    </dl>
    <form asp-action="Delete">
        <a href="/Tanilar/Index/@Model.Mid">LİSTEYE GERİ DÖN</a> &emsp;|&emsp;
        <input type="hidden" asp-for="Taniid" />
        <input type="submit" style="font-size:13px;font-weight:bold;height:27px;width:70px;" value="SİL" class="btn btn-danger" />

    </form>
</div>

bitproje/Views/Tanilar/Index.cshtml
@model IEnumerable<bitproje.Entitys.Tanilar>
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "Index";
}

<br />
<br />
<p>
    &emsp;
    @if (@Context.Session.GetString("grubu") == "A")
    {
        <a asp-action="Create" asp-route-id="@ViewBag.mid"><i style="font-size:20px;" class="fas fa-plus-circle" title="tanı ekle"></i> &nbsp; HASTA İÇİN TANI EKLE</a>
    }
    else if (@Context.Session.GetString("grubu") == "C")
    {
        <a asp-action="Create" asp-route-id="@ViewBag.mid"><i style="font-size:20px;" class="fas fa-plus-circle" title="tanı ekle"></i> &nbsp; HASTA İÇİN TANI EKLE</a>
    }
  
</p>

<table class="table">
    <thead>
        <tr>

            <th>
                TANI
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Tanim.Taniadi)
                </td>
                <td>
                    @if (@Context.Session.GetString("grubu") == "A")
                    {
                        <a asp-action="Delete" asp-route-id="@item.Taniid"><i class="fas fa-trash-alt" title="TANIYI CIKAR"></i></a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="Details" asp-controller="Muayene" asp-route-id="@ViewBag.mid">

        <img style="height:35px;" title="Listeye geri dön" src="~/images/Iconsmind-Outline-Back.ico" />
    </a>
</div>