bitproje/Controllers/EgitimlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using bitproje.Data;
using bitproje.Entitys;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace bitproje.Controllers
{
    public class EgitimlerController : Controller
    {
        private readonly isgContext _context;

        public EgitimlerController(isgContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var egitim = await _context.Egitimler.OrderBy(b => b.Egitimid).ToListAsync();
                foreach (var item in egitim)
                {
                    item.kullanici = (_context.Kullanici.FirstOrDefault(b => b.Sicilno == item.Sicilno));

                } return View(egitim);
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult Grupegitim()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var bul =  _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmagrubuid"));
            var kullanicii =  _context.Kullanici.Where(b => b.Grupid == bul.GrupId);
            var egitim = new List<Egitimler>();
            foreach (var i in kullanicii)  //
            {
                var eg= _context.Egitimler.Where(c => c.Sicilno == i.Sicilno);
                
                foreach (var j in eg)
                {
                    j.kullanici = _context.Kullanici.FirstOrDefault(b=>b.Sicilno==j.Sicilno);
                    egitim.Add(j);

                }
            }            

            return View("Index", egitim);
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult Firmaegitim()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var bul = _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmaid"));
            var kullanicii = _context.Kullanici.Where(b => b.Grupid == bul.GrupId);
            var egitim = new List<Egitimler>();
            foreach (var i in kullanicii)  //
            {
                var eg = _context.Egitimler.Where(c => c.Sicilno == i.Sicilno);

                foreach (var j in eg)
                {
                    j.kullanici = _context.Kullanici.FirstOrDefault(b => b.Sicilno == j.Sicilno);
                    egitim.Add(j);

                }
            }

            return View("Index", egitim);
            }
            else
            {
                return NotFound();
            }
        }
        public IActionResult kulFirmaegitim()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var egitim = _context.Egitimler.Where(b => b.Sicilno.ToString() == HttpContext.Session.GetString("sicilno"));
            
            foreach (var i in egitim)  //
            {
                i.kullanici = _context.Kullanici.FirstOrDefault(c => c.Sicilno == i.Sicilno);

            }

            return View("Index", egitim);
        }
            else
            {
                return NotFound();
    }
     }


        public IActionResult Create()
        {
            var egitim = new Egitimler();
            if (HttpContext.Session.GetString("grubu") == "A")
            {
                var bul = _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmagrubuid"));
                var kullanici = new List<Kullanici>( _context.Kullanici.Where(b => b.Grupid == bul.GrupId && b.Gorevtanim == "İşyeri Güvenliği Uzmanı"));              
                ViewBag.mkullanici = kullanici;
            }
             else  if (HttpContext.Session.GetString("grubu") == "D")
            {
                var kul = _context.Kullanici.FirstOrDefault(b => b.Sicilno.ToString() == HttpContext.Session.GetString("sicilno"));
                egitim.Sicilno = kul.Sicilno;
                egitim.kullanici = kul;
            }
            else
            {
                return NotFound();
            }


            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Egitimtrh,Egitimalani,Toplamsure,Aciklama,Egitimkonulari,Sicilno")]
        Egitimler eg)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eg);
                await _context.SaveChangesAsync();
                if (HttpContext.Session.GetString("grubu") == "A") { return RedirectToAction(nameof(Grupegitim)); }
                else if (HttpContext.Session.GetString("grubu") == "D") { return RedirectToAction(nameof(kulFirmaegitim)); }
            }

            return View(eg);

        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var egitim = await _context.Egitimler.FindAsync(id);
            if (egitim == null)
            {
                return NotFound();
            }
            if (HttpContext.Session.GetString("grubu") == "A")
            {
                var bul = _context.Firma.FirstOrDefault(b => b.Firmaid.ToString() == HttpContext.Session.GetString("firmagrubuid"));               
                var kullanici = new List<Kullanici>(_context.Kullanici.Where(b => b.Grupid == bul.GrupId && b.Gorevtanim == "İşyeri Güvenliği Uzmanı"));
                
                ViewBag.mkul = kullanici;
            }
            else if (HttpContext.Session.GetString("grubu") == "D")
            {
                var bul =_context.Kullanici.FirstOrDefault(b => b.Sicilno==egitim.Sicilno);
                egitim.kullanici = bul; 
            }
            else
            {
                return NotFound();
            }

            return View(egitim);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Egitimid,Egitimtrh,Egitimalani,Toplamsure,Aciklama,Egitimkonulari,Sicilno")]
        Egitimler eg)
        {
            if (id != eg.Egitimid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eg);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EgitimExists(eg.Egitimid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if (HttpContext.Session.GetString("grubu") == "A") { return RedirectToAction(nameof(Grupegitim)); }
                else if (HttpContext.Session.GetString("grubu") == "D") { return RedirectToAction(nameof(kulFirmaegitim)); }
            }

            return View(eg);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (HttpContext.Session.GetString("grubu") == "A" || HttpContext.Session.GetString("grubu") == "D")
            {
                var egitim = _context.Egitimler
                .FirstOrDefault(m => m.Egitimid == id);
                egitim.kullanici = _context.Kullanici.FirstOrDefault(b => b.Sicilno == egitim.Sicilno);
                if (egitim == null)
                {
                    return NotFound();
                }
                return View(egitim);
            }
            else
            {
                return NotFound();
            }

        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eg = _context.Egitimler.FirstOrDefault(m => m.Egitimid == id);
            _context.Egitimler.Remove(eg);
            await _context.SaveChangesAsync();
            if (HttpContext.Session.GetString("grubu") == "A") { return RedirectToAction(nameof(Grupegitim)); }
            else if (HttpContext.Session.GetString("grubu") == "D") { return RedirectToAction(nameof(kulFirmaegitim)); }
            return View();
        }


        private bool EgitimExists(int id)
        {
            return _context.Muayene.Any(e => e.Mid == id);
        }


    }
}

bitproje/Controllers/GrupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using bitproje.Data;
using bitproje.Entitys;
using bitproje.Models;
using bitproje.Utility;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace bitproje.Controllers
{
    public class GrupController : Controller
    {
        private readonly isgContext _context;

        public GrupController(isgContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                var Context = _context.Firma.Where(b => b.Durum.Equals("ANA FİRMA"));

            return View(Context.ToList());
            }
            else
            {
                return NotFound();
            }
        }
        public IActionResult Yönetim()
        {
            if (HttpContext.Session.GetString("grubu") =="A")
            {
                var Context = _context.Users.OrderBy(b=>b.Id);

            return View(Context.ToList());
            }
            else
            {
                return NotFound();
            }
        }


        public IActionResult Detayi(int? id)
        {
            if (HttpContext.Session.GetString("grubu") == "A")
            {
                var firma = _context.Firma.FirstOrDefault(b => b.Firmaid == id);
                HttpContext.Session.SetString("firmagrubuad", firma.Funvan);
                HttpContext.Session.SetString("firmagrubuid", firma.Firmaid.ToString());



                ViewBag.firmacount = _context.Firma.Count(b => b.GrupId == firma.GrupId);
                ViewBag.kullanicicount = _context.Kullanici.Count(b => b.Grupid == firma.GrupId);
                var firmaa = _context.Firma.Where(b => b.GrupId == firma.GrupId);
                //FİRMA GRUBUNA GÖRE FİRMANIN PERSONEL SAYISINI HESAPLAR
                int top = 0;
                foreach (var i in firmaa)
                {
                    top = top + _context.Personel.Count(b => b.Firmaid == i.Firmaid);

                }
                ViewBag.personelcount = top;

                //FİRMA GRUBUNA GÖRE FİRMANIN BİRİMLERİNİN SAYISINI HESAPLAR
                int topbirim = 0;
                foreach (var i in firmaa)
                {
                    topbirim = topbirim + _context.Birim.Count(b => b.Firmaid == i.Firmaid);

                }
                ViewBag.birimcount = topbirim;

                //FİRMA GRUBUNA GÖRE FİRMANIN muayene  SAYISINI HESAPLAR
                int topmuayene = 0;
                foreach (var i in firmaa)
                {
                    var personell = _context.Personel.Where(b => b.Firmaid == i.Firmaid);
                    foreach (var j in personell)
                    {
                        topmuayene = topmuayene + _context.Muayene.Count(b => b.Sicilnop == j.Sicilnop);


                    }

                }
                ViewBag.muayenecount = topmuayene;
                int topegitim = 0;
                var kul = _context.Kullanici.Where(b => b.Grupid == firma.GrupId);
                foreach (var i in kul)
                {
                    topegitim = topegitim + _context.Egitimler.Count(b => b.Sicilno == i.Sicilno);

                }
                ViewBag.egitimcount = topegitim;

                return View(firma);
            }
            else
            {
                return NotFound();
            }

            }


        public IActionResult Degis()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {

                var Context = _context.Firma.Where(b => b.Durum.Equals("ANA FİRMA"));

            return View(Context.ToList());
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {

                return View();
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Funvan,Isvrnadsoyad,Isvrngsm,Firmatlfn,Faks,Firmamail,Il,Ilce,Adres,Faaliyetalan,Sgksicil,Tehlikesinif,Grupsirket")]
        Firma fir)
        {
            if (ModelState.IsValid)
            {

                baglantiSinifi bs = new baglantiSinifi();
                string sorgu="insert into firmagruplari(grup_ad) values('"+fir.Funvan+"')";
                bs.baglanti("ekleme", sorgu);
                int a=bs.baglanti("bulgrubu", "");
                string sorgu1 = "insert into firma(funvan,isvrnadsoyad,isvrngsm,firmatlfn,faks,firmamail,il,ilce,adres,faaliyetalan,sgksicil,tehlikesinif,grupsirket,durum,grup_id) values" +
                    "('" + fir.Funvan + "','" + fir.Isvrnadsoyad + "','" + fir.Isvrngsm + "','" + fir.Firmatlfn + "','" + fir.Faks + "','" + fir.Firmamail + "','" + fir.Il + "','" + fir.Ilce + "','" + fir.Adres + "','" + fir.Faaliyetalan + "','" + fir.Sgksicil + "','" + fir.Tehlikesinif + "','" + fir.Grupsirket + "','ANA FİRMA','" + a + "')";
                bs.baglanti("ekleme", sorgu1);

                 a = bs.baglanti("bulfirma", "");
                var user = new Users
                {
                    Kullaniciadi = fir.Firmamail,
                    Sifre = "sıfırIsgm",
                    Firmaid = a,
                    Grubu = "B"
                };
                _context.Add(user);
                await _context.SaveChangesAsync();
                ViewBag.sonuc = "FİRMA Eklendi";
                return RedirectToAction(nameof(Index));
            }
           
            return View(fir);
        }





        public async Task<IActionResult> Delete(int? id)
        {
            if (HttpContext.Session.GetString("grubu") != null)
            {
                if (id == null)
            {
                return NotFound();
            }

            var fir = _context.Firma
                .FirstOrDefaultAsync(m => m.Firmaid == id);
            if (fir == null)
            {
                return NotFound();
            }

            return View(await fir);
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fir = _context.Firma.FirstOrDefault(m => m.Firmaid == id);
            var grup = _context.Firmagruplari.FirstOrDefault(a => a.GrupId == fir.GrupId);
            _context.Firmagruplari.Remove(grup);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }





        public IActionResult Kayit()
        {
            return View();
        }
        public IActionResult Record()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Kayit([Bind("Funvan,Isvrnadsoyad,Isvrngsm,Firmatlfn,Faks,Firmamail,Il,Ilce,Adres,Faaliyetalan,Sgksicil,Tehlikesinif,Grupsirket")]
        Firma fir)
        {
            if (ModelState.IsValid)
            {

                baglantiSinifi bs = new baglantiSinifi();
                string sorgu = "insert into firmagruplari(grup_ad) values('" + fir.Funvan + "')";
                bs.baglanti("ekleme", sorgu);
                int a = bs.baglanti("bulgrubu", "");
                string sorgu1 = "insert into firma(funvan,isvrnadsoyad,isvrngsm,firmatlfn,faks,firmamail,il,ilce,adres,faaliyetalan,sgksicil,tehlikesinif,grupsirket,durum,grup_id) values" +
                    "('" + fir.Funvan + "','" + fir.Isvrnadsoyad + "','" + fir.Isvrngsm + "','" + fir.Firmatlfn + "','" + fir.Faks + "','" + fir.Firmamail + "','" + fir.Il + "','" + fir.Ilce + "','" + fir.Adres + "','" + fir.Faaliyetalan + "','" + fir.Sgksicil + "','" + fir.Tehlikesinif + "','" + fir.Grupsirket + "','ANA FİRMA','" + a + "')";
                bs.baglanti("ekleme", sorgu1);
                ViewBag.sonuc = "FİRMA Eklendi";
                a = bs.baglanti("bulfirma", "");
                return RedirectToAction("FirmaKayit", "Register", new { id = a });
            }
            
            return View(fir);
        }





   


    }
}

bitproje/Views/Grup/Create.cshtml
@model bitproje.Entitys.Firma

@{
    ViewData["Title"] = "Create";
}


<h4>FİRMA GRUBU EKLE</h4>
<hr />
<div class="row">
    <form asp-action="Create">
        <div class="col-md-4">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">FİRMA AD</label>
                <input asp-for="Funvan" class="form-control" />
                <span asp-validation-for="Funvan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">İŞ VEREN KİŞİ</label>
                <input asp-for="Isvrnadsoyad" class="form-control" />
                <span asp-validation-for="Isvrnadsoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">İŞ VEREN GSM</label>
                <input asp-for="Isvrngsm" class="form-control" />
                <span asp-validation-for="Isvrngsm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">FİRMA TELEFON</label>
                <input asp-for="Firmatlfn" class="form-control" />
                <span asp-validation-for="Firmatlfn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">FAKS</label>
                <input asp-for="Faks" class="form-control" />
                <span asp-validation-for="Faks" class="text-danger"></span>
            </div>



        </div>
        <div class="col-md-4">

            <div class="form-group">
                <label class="control-label">FİRMA MAİL</label>
                <input asp-for="Firmamail" class="form-control" />
                <span asp-validation-for="Firmamail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">İL</label>
                <input asp-for="Il" class="form-control" />
                <span asp-validation-for="Il" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">İLÇE</label>
                <input asp-for="Ilce" class="form-control" />
                <span asp-validation-for="Ilce" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">ADRES</label>
                <input asp-for="Adres" class="form-control" />
                <span asp-validation-for="Adres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">FAALİYET ALANI</label>
                <input asp-for="Faaliyetalan" class="form-control" />
                <span asp-validation-for="Faaliyetalan" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">

            <div class="form-group">
                <label class="control-label">SGK SİCİL</label>
                <input asp-for="Sgksicil" class="form-control" />
                <span asp-validation-for="Sgksicil" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">TEHLİKE SINIFI</label>
                <select asp-for="Tehlikesinif" class="form-control">
                    <option value="AZ TEHLİKELİ">AZ TEHLİKELİ</option>
                    <option value="TEHLİKELİ">TEHLİKELİ</option>
                    <option value="ÇOK TEHLİKELİ">ÇOK TEHLİKELİ</option>
                </select>
                <span asp-validation-for="Tehlikesinif" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">GRUP ŞİRKET ?</label>
                <select asp-for="Grupsirket" class="form-control">
                    <option value="EVET">EVET</option>
                    <option value="HAYIR">HAYIR</option>
                </select>
                <span asp-validation-for="Grupsirket" class="text-danger"></span>
            </div>

            <div class="form-group">
                &emsp; &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                <input type="submit" value="EKLE" class="btn btn-info" />
            </div>
            @if (ViewBag.sonuc != null)
            {
                <p class="alert alert-success"> @ViewBag.sonuc</p>
            }
        </div>
    </form>
</div>

<div>
    <a asp-action="Index">

        <img style="height:35px;" title="Listeye geri dön" src="~/images/Iconsmind-Outline-Back.ico" />
    </a>
</div>

bitproje/Views/Grup/Kayit.cshtml
@model bitproje.Entitys.Firma
@{
    Layout = null;
}

<!DOCTYPE html>
<style>


    body {
        font-family: Verdana, monospace, sans-serif;
        font-size: 12px;
        font-weight: bold;
        text-align: justify;
        min-height: 800px;
        background: #52aa6f; /* Old browsers */
        background: -moz-linear-gradient(top, #52aa6f 0%, #4096ee 100%); /* FF3.6+ */
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#52aa6f), color-stop(100%,#4096ee)); /* Chrome,Safari4+ */
        background: -webkit-linear-gradient(top, #52aa6f 0%,#4096ee 100%); /* Chrome10+,Safari5.1+ */
        background: -o-linear-gradient(top, #52aa6f 0%,#4096ee 100%); /* Opera 11.10+ */
        background: -ms-linear-gradient(top, #52aa6f 0%,#4096ee 100%); /* IE10+ */
        background: linear-gradient(to bottom, #52aa6f 0%,#4096ee 100%); /* W3C */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#52aa6f', endColorstr='#4096ee',GradientType=0 ); /* IE6-9 */
    }
</style>


<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bitproje</title>


    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
              integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ"
              crossorigin="anonymous" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <title>Login</title>
</head>


<body class="text-center">

    <div>

        <div class="col-md-1"></div>
        <div class="col-md-10" style="background-color:white;border-radius: 40px;height:500px;">
            <br />
            <br />
            <form method="post" asp-controller="Grup" asp-action="Kayit">
                <div class="col-md-4">

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label class="control-label">FİRMA AD*</label>
                        <input asp-for="Funvan" class="form-control" required="" />
                        <span asp-validation-for="Funvan" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">İŞ VEREN KİŞİ*</label>
                        <input asp-for="Isvrnadsoyad" class="form-control" required="" />
                        <span asp-validation-for="Isvrnadsoyad" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">İŞ VEREN GSM*</label>
                        <input asp-for="Isvrngsm" class="form-control" required="" />
                        <span asp-validation-for="Isvrngsm" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">FİRMA TELEFON*</label>
                        <input asp-for="Firmatlfn" class="form-control" required="" />
                        <span asp-validation-for="Firmatlfn" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">FAKS*</label>
                        <input asp-for="Faks" class="form-control" required="" />
                        <span asp-validation-for="Faks" class="text-danger"></span>
                    </div>



                </div>
                <div class="col-md-4">

                    <div class="form-group">
                        <label class="control-label">FİRMA MAİL*</label>
                        <input asp-for="Firmamail" class="form-control" required="" />

                        <span asp-validation-for="Firmamail" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">İL*</label>
                        <input asp-for="Il" class="form-control" required="" />
                        <span asp-validation-for="Il" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">İLÇE*</label>
                        <input asp-for="Ilce" class="form-control" required="" />
                        <span asp-validation-for="Ilce" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">ADRES*</label>
                        <input asp-for="Adres" class="form-control" required="" />
                        <span asp-validation-for="Adres" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">FAALİYET ALANI*</label>
                        <input asp-for="Faaliyetalan" class="form-control" required="" />
                        <span asp-validation-for="Faaliyetalan" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">

                    <div class="form-group">
                        <label class="control-label">SGK SİCİL*</label>
                        <input asp-for="Sgksicil" class="form-control" pattern="\d{23}" title="SGK SİCİL 23 haneli olmak zorunda" required="" />
                        <span asp-validation-for="Sgksicil" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">TEHLİKE SINIFI*</label>
                        <select asp-for="Tehlikesinif" class="form-control">
                            <option value="AZ TEHLİKELİ">AZ TEHLİKELİ</option>
                            <option value="TEHLİKELİ">TEHLİKELİ</option>
                            <option value="ÇOK TEHLİKELİ">ÇOK TEHLİKELİ</option>
                        </select>
                        <span asp-validation-for="Tehlikesinif" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="control-label">GRUP ŞİRKET ?</label>
                        <select asp-for="Grupsirket" class="form-control">
                            <option value="EVET">EVET</option>
                            <option value="HAYIR">HAYIR</option>
                        </select>
                        <span asp-validation-for="Grupsirket" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        &emsp; &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                        <input type="submit" value="KAYIT OL" class="btn btn-info" />
                    </div>
                    @if (ViewBag.sonuc != null)
                    {
                        <p class="alert alert-success"> @ViewBag.sonuc</p>
                    }
                </div>
            </form>
            <div>

            </div>
            &emsp;&emsp;&emsp;
            <a asp-action="ISGM" asp-controller="Home">

                <img style="height:35px;" title="Listeye geri dön" src="~/images/Iconsmind-Outline-Back.ico" />
            </a>
        </div>
    </div>
</body>

</html>